export const API_ROUTES = {
  AUTH: "/api/auth",
  CONTACT: "/api/contact",
  BETA_FEEDBACK: "/api/beta-feedback",
  USERS: "/api/users",
  HEALTH: "/api/health",
  INSTRUCTOR: "/api/instructor",
  COURSE: "/api/course",
  COURSE_PROGRESS: "/api/course/progress",
  COURSE_REVIEWS: "/api/course/review",
  PRACTICE: "/api/practice",
  VIDEO: "/api/video",
  ADMIN: "/api/admin",
  MP: "/api/mp",
  COMMERCE: "/api/commerce",
} as const;
