export * from "./authEndpoints";
export * from "./instructorEndpoint";
export * from "./courseEndpoints";
export * from "./usersEndpoints";
export * from "./adminEndpoints";
export * from "./mpEndpoints";
export * from "./practiceEndpoints";
export * from "./commerceEndpoints";
export * from "./contactEndpoints";
